load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary", "cc_test")

cc_library(
    name = "gsl",
    srcs = [],
    hdrs = [],
    includes = ["/usr/include"],  # Change if necessary
    linkopts = ["-lgsl", "-lgslcblas"],  # Link GSL and CBLAS
    visibility = ["//visibility:public"],
)

cc_library(
    name="spherical_harmonic_models",
    srcs=["spherical_harmonic_models.cc"],
    hdrs=["spherical_harmonic_models.h"],
    deps=[":gsl", ":math"],
    data=["//coeffs:coeffs"],
)

cc_library(
    name="wgs84",
    hdrs=["wgs84.h"],
)

cc_library(
    name="math",
    srcs=["math.cc"],
    hdrs=["math.h"],
    deps=[":gsl", ":time", ":wgs84"]
)

cc_library(
    name="conversions",
    srcs=["conversions.cc"],
    hdrs=["conversions.h"],
)

cc_test(
    name="conversions_test",
    srcs=["conversions_test.cc"],
    deps=[
        ":conversions",
        "@googletest//:gtest_main"
    ],
)

cc_library(
    name="time",
    srcs=["time.cc"],
    hdrs=["time.h"],
)

cc_library(
    name="utils",
    srcs=["utils.cc"],
    hdrs=["utils.h"],
)

cc_test(
    name="utils_test",
    srcs=["utils_test.cc"],
    deps=[
        ":utils",
        "@googletest//:gtest_main",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    data=["//dat/utils_test:test_files"],
    defines=["BAZEL_UNIT_TEST_MODE"],
)

cc_library(
    name="json",
    srcs=["json.cc"],
    hdrs=["json.h"],
    deps=[":utils"],
)

cc_test(
    name="json_test",
    srcs=["json_test.cc"],
    deps=[
        ":json",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name="main",
    srcs=["main.cc"],
    deps=[":utils"],
)
